name: Deploy Spring Boot to Amazon ECS

on:
  push:
    branches:
      - "master"

env:
  AWS_REGION: ca-central-1              
  ECR_REPOSITORY: aws
  ECS_SERVICE: ecs-service
  ECS_CLUSTER: ecs-cluster
  ECS_TASK_DEFINITION: .github/workflows/ecs-task-definition.json
  CONTAINER_NAME: aws-container

permissions:
  id-token: write
  contents: read # This is required for actions/checkout@v2

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Build with Maven
      run: mvn clean install --file pom.xml

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: 
        aws-secret-access-key: 
        aws-region: ca-central-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: aws
        IMAGE_TAG: 1.1
      run: |
        # Build a docker container and push it to ECR so that it can be deployed to ECS.
        aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/x4l5q5n0
        docker build -t faizanzameer/aws:1.1 .
        docker tag faizanzameer/aws:1.1 public.ecr.aws/x4l5q5n0/faizanzameer/aws:1.1
        docker push public.ecr.aws/x4l5q5n0/faizanzameer/aws:1.1
        echo "::set-output name=image::public.ecr.aws/x4l5q5n0/faizanzameer/aws:1.1"
    - name: Fill in the new image ID in the Amazon ECS task definition
      id: task-def
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: .github/workflows/ecs-task-definition.json
        container-name: aws-container
        image: ${{ steps.build-image.outputs.image }}

    - name: Deploy Amazon ECS task definition
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: .github/workflows/ecs-task-definition.json
        service: ecs-service
        cluster: ecs-cluster
        wait-for-service-stability: true
